### ISSUE TITLE
sourcemod version 1.12 7164

### ISSUE THREAD

**Issue by SmeraldoTAT** [SilvDev/Left4DHooks#14]
L 10/22/2024 - 00:00:41: SourceMod error session started
L 10/22/2024 - 00:00:41: Info (map "c1m1_hotel") (file "d:\steam\steamapps\common\left 4 dead 2\left4dead2\addons\sourcemod\logs\errors_20241022.log")
L 10/22/2024 - 00:00:41: [SM] Exception reported: Invalid private forward handle 0 (error 4)
L 10/22/2024 - 00:00:41: [SM] Blaming: left4dhooks.smx
L 10/22/2024 - 00:00:41: [SM] Call stack trace:
L 10/22/2024 - 00:00:41: [SM]   [0] PrivateForward.RemoveAllFunctions
L 10/22/2024 - 00:00:41: [SM]   [1] Line 1010, C:\Servers\L4D2\left4dead2\addons\sourcemod\scripting\left4dhooks.sp::OnMapEnd
L 10/22/2024 - 00:00:42: Error log file session closed.

**Comment by SilvDev** [comment]
Seems like a rare bug within SM, nothing I can do.
