### ISSUE TITLE
Missing gamedata

### ISSUE THREAD

**Issue by Anarki1980** [SilvDev/Left4DHooks#15]
After building the latest master we now get this:
L 10/28/2024 - 20:08:24: [SM] Exception reported: GameRulesPtr not available (NIX/2/1.153).
L 10/28/2024 - 20:08:24: [SM] Blaming: left4dhooks.smx
L 10/28/2024 - 20:08:24: [SM] Call stack trace:
L 10/28/2024 - 20:08:24: [SM]   [0] ThrowNativeError
L 10/28/2024 - 20:08:24: [SM]   [1] Line 190, l4dd\l4dd_natives.sp::ValidateAddress
L 10/28/2024 - 20:08:24: [SM]   [2] Line 4024, l4dd\l4dd_natives.sp::Direct_GetVSCampaignScore
L 10/28/2024 - 20:08:24: [SM]   [4] L4D2Direct_GetVSCampaignScore
L 10/28/2024 - 20:08:24: [SM]   [5] Line 77, proper_events.sp::OnMapStart

GameRulesPtr value is missing from sourcemod/gamedata/left4dhooks.l4d2.txt

**Comment by SilvDev** [comment]
Using L4D2Direct_GetVSCampaignScore from OnMapStart you need to call L4D_HasMapStarted, if that is false you need to use RequestFrame to call L4D2Direct_GetVSCampaignScore after. Will clarify the include file next update.
