### ISSUE TITLE
Failed to load "UseHealingItems" signature.

### ISSUE THREAD

**Issue by lovekanbekotori** [SilvDev/Left4DHooks#3]
L 05/31/2022 - 18:54:44: [left4dhooks.smx] Failed to find signature: ForceNextStage
L 05/31/2022 - 18:54:44: [left4dhooks.smx] Failed to find signature: CancelStagger
L 05/31/2022 - 18:54:44: [left4dhooks.smx] Failed to find signature: RegisterForbiddenTarget
L 05/31/2022 - 18:54:44: [left4dhooks.smx] Failed to find signature: UnRegisterForbiddenTarget
L 05/31/2022 - 18:54:44: [left4dhooks.smx] Failed to load "UseHealingItems" signature.
left4dhooks is already the latest version on github
l4d2 server versoin 2225
sourcemod versoin 1.10.0.6497

**Comment by SilvDev** [comment]
You have a duplicate version running or something else bugged before this. A server restart should fix. The error message `Failed to load "UseHealingItems" signature.` does not appear in the plugin, maybe an old or modified version? Recommend checking for duplicate left4dhooks plugin.
